@Riebreab.Api_HostAddress = http://localhost:5236

GET {{Riebreab.Api_HostAddress}}/api/items
Accept: application/json

###

POST {{Riebreab.Api_HostAddress}}/api/items
Content-Type: application/json

{
  "name": "First item",
  "description": "Created via .http file"
}

###

GET {{Riebreab.Api_HostAddress}}/api/items/1
Accept: application/json

###

PUT {{Riebreab.Api_HostAddress}}/api/items/1
Content-Type: application/json

{
  "name": "Updated item",
  "description": "Updated via .http file"
}

###

DELETE {{Riebreab.Api_HostAddress}}/api/items/1

###
